/** Swedish / English labels for normalized annual report financial keys (UI + API). */
export const CANONICAL_FINANCIAL_LABELS: Record<string, string> = {
  revenue: 'Nettoomsättning / intäkter',
  other_operating_income: 'Övriga rörelseintäkter',
  operating_expenses: 'Rörelsekostnader',
  personnel_costs: 'Personalkostnader',
  depreciation_amortization: 'Avskrivningar / nedskrivningar',
  operating_profit: 'Rörelseresultat',
  financial_result: 'Finansiella poster (netto)',
  profit_after_financial: 'Resultat efter finansiella poster',
  appropriations: 'Dispositioner / överskott',
  tax_on_profit: 'Skatt på årets resultat',
  net_profit: 'Årets resultat',
  intangible_assets: 'Immateriella tillgångar',
  tangible_assets: 'Materiella tillgångar',
  financial_assets: 'Finansiella tillgångar',
  total_fixed_assets: 'Anläggningstillgångar',
  inventory: 'Varulager',
  receivables: 'Kundfordringar / fordringar',
  cash_and_equivalents: 'Kassa och bank / likvida medel',
  total_current_assets: 'Omsättningstillgångar',
  total_assets: 'Summa tillgångar',
  equity: 'Eget kapital',
  share_capital: 'Aktiekapital',
  unrestricted_equity: 'Fritt eget kapital',
  restricted_equity: 'Bundet eget kapital',
  untaxed_reserves: 'Obeskattade reserver',
  provisions: 'Avsättningar',
  long_term_liabilities: 'Långfristiga skulder',
  short_term_liabilities: 'Kortfristiga skulder',
  accounts_payable: 'Leverantörsskulder',
  tax_liabilities: 'Skatteskulder',
  total_equity_and_liabilities: 'Summa eget kapital och skulder',
  operating_cash_flow: 'Kassaflöde från rörelse',
  investing_cash_flow: 'Kassaflöde från investeringar',
  financing_cash_flow: 'Kassaflöde från finansiering',
  cash_flow_for_year: 'Kassaflöde för året',
  cash_beginning: 'Likvida medel vid årets början',
  cash_end: 'Likvida medel vid årets slut',
  employee_count: 'Antal anställda',
  dividends: 'Utdelning',
  interest_income: 'Ränteintäkter',
  interest_expense: 'Räntekostnader',
};
