export default () => ({
  NODE_ENV: process.env.NODE_ENV ?? 'development',
  PORT: Number(process.env.PORT ?? 4000),
  PG_HOST: process.env.PG_HOST ?? 'localhost',
  PG_PORT: Number(process.env.PG_PORT ?? 5432),
  PG_DBNAME: process.env.PG_DBNAME ?? 'Company',
  PG_USER: process.env.PG_USER ?? 'postgres',
  PG_PASSWORD: process.env.PG_PASSWORD ?? 'postgres',
  DATABASE_URL: process.env.DATABASE_URL,
  REDIS_HOST: process.env.REDIS_HOST ?? 'localhost',
  REDIS_PORT: Number(process.env.REDIS_PORT ?? 6379),
  REDIS_PASSWORD: process.env.REDIS_PASSWORD ?? '',
  JWT_SECRET: process.env.JWT_SECRET,
  JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,
  INTEGRATION_TOKEN_ENCRYPTION_KEY: process.env.INTEGRATION_TOKEN_ENCRYPTION_KEY,
  MINIO_ENDPOINT: process.env.MINIO_ENDPOINT ?? 'localhost',
  MINIO_PORT: Number(process.env.MINIO_PORT ?? 9000),
  MINIO_USE_SSL: process.env.MINIO_USE_SSL === 'true',
  MINIO_REGION: process.env.MINIO_REGION ?? 'eu-west-1',
  MINIO_ROOT_USER: process.env.MINIO_ROOT_USER,
  MINIO_ROOT_PASSWORD: process.env.MINIO_ROOT_PASSWORD,
  AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
  S3_BUCKET: process.env.S3_BUCKET ?? 'verifyiq-documents',
  BV_CLIENT_ID: process.env.BV_CLIENT_ID,
  BV_CLIENT_SECRET: process.env.BV_CLIENT_SECRET,
  BV_HVD_CLIENT_ID: process.env.BV_HVD_CLIENT_ID,
  BV_HVD_CLIENT_SECRET: process.env.BV_HVD_CLIENT_SECRET,
  BV_HVD_BASE_URL: process.env.BV_HVD_BASE_URL,
  BV_HVD_TOKEN_URL: process.env.BV_HVD_TOKEN_URL,
  BV_HVD_REVOKE_URL: process.env.BV_HVD_REVOKE_URL,
  BV_HVD_SCOPES: process.env.BV_HVD_SCOPES,
  BV_HVD_DOCUMENT_PATH: process.env.BV_HVD_DOCUMENT_PATH,
  BV_FORETAGSINFO_BASE_URL: process.env.BV_FORETAGSINFO_BASE_URL,
  BV_FORETAGSINFO_AUTH_HEADER: process.env.BV_FORETAGSINFO_AUTH_HEADER,
  BV_FORETAGSINFO_AUTH_VALUE: process.env.BV_FORETAGSINFO_AUTH_VALUE,
  BV_FORETAGSINFO_BEARER_TOKEN: process.env.BV_FORETAGSINFO_BEARER_TOKEN,
  BV_FORETAGSINFO_AUTH_TOKEN: process.env.BV_FORETAGSINFO_AUTH_TOKEN,
  BV_FORETAGSINFO_TOKEN: process.env.BV_FORETAGSINFO_TOKEN,
  API_BASE_URL: process.env.API_BASE_URL ?? 'http://localhost:4000/api/v1',
  FRONTEND_URL: process.env.FRONTEND_URL,
  FRONTEND_URLS: process.env.FRONTEND_URLS,
});
